# Command to create a csv file to use in taxonomy assignment step 
# Input:
# ASVs,Sequences
# ,AGCTATTGTGTGTTCAGATATGTTAAAGCCACTTTCGTAGTCTATTTTGTGTCAACTGGAGTTTTTTACAACTCAGGTGAGTTTTAGCTTTATTGGGGAGGGGGTGATCTAAAACACTCTTTACGCCGGCTTCTATTGACTTGGGTTAATCGTGTGACCGCGGTGGCTGGC
# ,AGCTATTGTGTGTTCAGATATGTTAAAGCCACTTTCGTAGTCTATTTTGTGTCAACTGGAGTTTTTTACAACTCAGGTGAGTTTTAGCTTTATTGGGGAGGGGGTGATCTAAAACACTCTTTACGCCGGCTTCTATTGACTTGGGTTAATCGTGTGACCGCGGTGGCTG
# ,ACGATTAACCCAAGTCAATAGAAGCCGGCGTAAAGAGTGTTTTAGATCACCCCCTCCCCAATAAAGCTAAAACTCACCTGAGTTGTAAAAAACTCCAGTTGACACAAAATAGACTACGAAAGTGGCTTTAACATATCTGAACACACAATAGCTAAGACCCAAACTGGGA
# I just paste transpose the first line of the file nochim_seq_12S.csv and save in csv file as well.


import pandas as pd

# Read the CSV file (works for both comma or tab-separated files)
df = pd.read_csv("your_file.csv")  # Replace with your file path

# Choose the starting number for X (e.g., 1, 100, etc.)
start_number = 1  # Change this as needed

# Generate ASV names (ASV1, ASV2, ...)
df['ASVs'] = ['ASV' + str(i + start_number) for i in range(len(df))]

# Save the modified DataFrame to a new CSV file
df.to_csv("ASV_lib1_12S_tax.csv", index=False)

# Output
# ASVs,Sequences
# ASV1,AGCTATTGTGTGTTCAGATATGTTAAAGCCACTTTCGTAGTCTATTTTGTGTCAACTGGAGTTTTTTACAACTCAGGTGAGTTTTAGCTTTATTGGGGAGGGGGTGATCTAAAACACTCTTTACGCCGGCTTCTATTGACTTGGGTTAATCGTGTGACCGCGGTGGCTGGC
# ASV2,AGCTATTGTGTGTTCAGATATGTTAAAGCCACTTTCGTAGTCTATTTTGTGTCAACTGGAGTTTTTTACAACTCAGGTGAGTTTTAGCTTTATTGGGGAGGGGGTGATCTAAAACACTCTTTACGCCGGCTTCTATTGACTTGGGTTAATCGTGTGACCGCGGTGGCTG
# ASV3,ACGATTAACCCAAGTCAATAGAAGCCGGCGTAAAGAGTGTTTTAGATCACCCCCTCCCCAATAAAGCTAAAACTCACCTGAGTTGTAAAAAACTCCAGTTGACACAAAATAGACTACGAAAGTGGCTTTAACATATCTGAACACACAATAGCTAAGACCCAAACTGGGA
